import Link from "next/link";
import { notFound } from "next/navigation";
import { getContract } from "@/lib/data/contracts";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const contract = await getContract(Number(id));
  if (!contract) notFound();
  const details = [["Дата", contract.contract_date], ["Услуга", contract.service_type], ["Сумма", contract.amount === null ? null : `${contract.amount} ${contract.currency}`], ["Срок исполнения", contract.execution_days && `${contract.execution_days} дней`], ["Срок оплаты", contract.payment_days && `${contract.payment_days} дней`], ["Редакция", contract.revision]];
  return <div className="space-y-6"><Link href="/contracts" className="text-sm font-semibold text-red-700">К реестру</Link><section className="rounded-2xl border bg-white p-6 shadow-panel"><div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">{contract.contract_number}</h1><p className="mt-2 text-slate-500">{contract.client_name ?? "Клиент не указан"}</p><p className="mt-2 text-sm">{contract.status}</p></div><Link href={`/contracts/${contract.id}/edit`} className="rounded-xl border px-4 py-3 font-semibold">Редактировать</Link></div><dl className="mt-6 grid gap-4 md:grid-cols-2">{details.map(([label, value]) => <div key={String(label)}><dt className="text-xs uppercase text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value || "—"}</dd></div>)}</dl>{contract.drive_folder_url && <a className="mt-6 inline-block text-red-700" href={contract.drive_folder_url} target="_blank">Открыть папку Drive</a>}</section><section className="rounded-2xl border bg-white p-6 shadow-panel"><h2 className="text-xl font-bold">Документы договора</h2>{contract.documents.length ? <ul className="mt-4 divide-y">{contract.documents.map((document) => <li key={document.id} className="flex items-center justify-between gap-4 py-3"><Link href={`/documents/${document.id}`} className="font-semibold text-red-700">{document.title}</Link><span className="text-sm text-slate-500">{document.document_number ?? "Без номера"} · {document.status}</span></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">Связанные документы не найдены.</p>}</section></div>;
}
