"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { ExpertReview } from "@/lib/data/expert-reviews";

type Option = { id: number; label: string };
export function ExpertReviewForm({ projects, documents, item }: { projects: Option[]; documents: Option[]; item?: ExpertReview }) {
  const router = useRouter(); const [error, setError] = useState("");
  const [value, setValue] = useState({ project_id: String(item?.project_id ?? ""), document_id: item?.document_id ? String(item.document_id) : "", title: item?.title ?? "", description: item?.description ?? "", normative_reference: item?.normative_reference ?? "", severity: item?.severity ?? "normal", status: item?.status ?? "open", resolution: item?.resolution ?? "" });
  const set = (key: keyof typeof value, next: string) => setValue((previous) => ({ ...previous, [key]: next }));
  async function submit(event: FormEvent) { event.preventDefault(); const supabase = createClient(); if (!supabase) return setError("Supabase не настроен."); const payload = { p_project_id: Number(value.project_id), p_document_id: value.document_id ? Number(value.document_id) : null, p_title: value.title, p_description: value.description || null, p_normative_reference: value.normative_reference || null, p_severity: value.severity, p_status: value.status, p_resolution: value.resolution || null }; const result = item ? await supabase.rpc("update_expert_review", { p_id: item.id, ...payload }) : await supabase.rpc("create_expert_review", payload); if (result.error) return setError(result.error.message); const data: any = result.data; router.push(`/expert-reviews/${item?.id ?? (Array.isArray(data) ? data[0]?.id : data?.id)}`); router.refresh(); }
  return <form onSubmit={submit} className="mx-auto max-w-3xl space-y-5 rounded-2xl border bg-white p-6"><h1 className="text-3xl font-bold">{item ? "Редактирование замечания" : "Новое замечание"}</h1><div className="grid gap-5 md:grid-cols-2"><label><span>Проект *</span><select className="input" value={value.project_id} onChange={(event) => set("project_id", event.target.value)} required><option value="">Не выбран</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.label}</option>)}</select></label><label><span>Документ</span><select className="input" value={value.document_id} onChange={(event) => set("document_id", event.target.value)}><option value="">Не выбран</option>{documents.map((document) => <option key={document.id} value={document.id}>{document.label}</option>)}</select></label><label className="md:col-span-2"><span>Замечание *</span><input className="input" value={value.title} onChange={(event) => set("title", event.target.value)} required /></label><label className="md:col-span-2"><span>Описание</span><textarea className="input min-h-28" value={value.description} onChange={(event) => set("description", event.target.value)} /></label><label><span>Нормативная ссылка</span><input className="input" value={value.normative_reference} onChange={(event) => set("normative_reference", event.target.value)} /></label><label><span>Критичность</span><select className="input" value={value.severity} onChange={(event) => set("severity", event.target.value)}><option value="critical">Критическое</option><option value="major">Существенное</option><option value="normal">Обычное</option><option value="minor">Незначительное</option></select></label><label><span>Статус</span><select className="input" value={value.status} onChange={(event) => set("status", event.target.value)}><option value="open">Открыто</option><option value="in_progress">В работе</option><option value="resolved">Устранено</option></select></label><label><span>Результат устранения</span><input className="input" value={value.resolution} onChange={(event) => set("resolution", event.target.value)} /></label></div>{error && <p className="text-red-700">{error}</p>}<div className="flex justify-end"><button className="rounded-xl bg-red-700 px-5 py-3 text-white">Сохранить</button></div></form>;
}
